---
apiVersion: v1
kind: Namespace
metadata:
  name: mosquitto

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mosquitto
data:
  mosquitto.conf: |-
    persistence true
    persistence_location /mosquitto/data
    allow_anonymous false
    connection_messages true
    log_type all
    listener 1883
    password_file /mosquitto/passwd/password_file

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data-claim
  namespace: mosquitto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      securityContext:
        fsGroup: 1883
      containers:
        - name: mosquitto
          image: ks89/mosquitto
          imagePullPolicy: Never  # use the locally loaded image
          env:
            - name: MOSQUITTO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mosquitto-auth
                  key: username
            - name: MOSQUITTO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mosquitto-auth
                  key: password
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 10
            periodSeconds: 60
          volumeMounts:
            - name: data
              mountPath: /mosquitto/data
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
              readOnly: true
            - name: passwd
              mountPath: /mosquitto/passwd
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data-claim
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
        - name: passwd
          emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: mqtt