user device_pubsub
topic write sensors/+/+
topic write online/+/features/+
topic read devices/+/values

user producer_sub
topic read sensors/+/+

user online_receiver_sub
topic read online/+/features/+

user api_devices_pub
topic write devices/+/values
