user device_pubsub
topic write sensors/+/+
topic write online/+/features/+
topic write alarms/+/features/+/+
topic read devices/+/values

user producer_sub
topic read sensors/+/+

user alarm_receiver_sub
topic read online/+/features/+
topic read alarms/+/features/+/+

user api_devices_pub
topic write devices/+/values
